name: Sync to Hugging Face hub
on:
    push:
        brnaches: [main]
    
    # to run this workflow manually from Actions tab

    workflow_dispatch:
jobs:
    sync-to-hub:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth:
                lfs: false
            
            - name: Ignore large files
              run:  git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch "Rag_Documents/layout-parser-paper.pdf"' HEAD

            - name: Push to hub
              env:
                    HF_TOKEN : ${{ secrets.HF_TOKEN}}
                run: git push --force https://Ganu811:$HF_TOKEN@huggingface.co/spaces/Ganu811/AgenticAI main