name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Ignore large files
        run: git filter-branch --index-filter 'git rm -rf --cached --ignore-unmatch "Rag_Documents/layout-parser-paper.pdf"' HEAD

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://Ganu811:${{ env.HF_TOKEN }}@huggingface.co/spaces/Ganu811/AgenticAI main